# This file is based on the quickstart.yaml file which accompanies the ory/kratos package.
# https://github.com/ory/kratos/blob/master/quickstart.yml

# Updated from 3.7
version: "3.9"

services:
  ## Initialize Kratos storage; populate SQLite database.
  kratos-migrate:
    container_name: kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc # Docs->Reference->Configuration->Data Source Name
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql sql -e --yes # https://www.ory.sh/kratos/docs/cli/kratos-migrate-sql
    restart: on-failure
    networks:
      - intranet

  ## Running Kratos instance which will serve-requests.
  kratos:
    container_name: kratos
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1-sqlite
    ports:
      - "4433:4433" # Public Endpoints https://www.ory.sh/kratos/docs/reference/api#public-endpoints
      - "4434:4434" # Administrative Endpoints https://www.ory.sh/kratos/docs/reference/api#administrative-endpoints
    restart: unless-stopped # Always restart if the container stops.
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet

  ## Optional to test E-Mail functionality of Kratos; i.e. verification, recovery.
  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-sqlite:
